# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-76wW4kOgAXu9AEug5TCWuTKRCpMWmfH
"""



LIMITE_SEGURANCA = 15000.00

def analisar_vendas():
    global LIMITE_SEGURANCA
    print("--- Sistema de Auditoria de Vendas ---")

    try:

        v1 = float(input("Digite o valor da venda 1: "))
        v2 = float(input("Digite o valor da venda 2: "))
        v3 = float(input("Digite o valor da venda 3: "))
        vendas = [v1, v2, v3]


        media = sum(vendas) / len(vendas)
        print(f"\nMédia calculada: R$ {media:.2f}")


        for v in vendas:
            if v > (media * 5):
                print(f"\nALERTA: Discrepância detectada na venda de R$ {v:.2f}.")
                print("Sugestão: REVISÃO MANUAL.")

                # Permitir que o gerente altere o LIMITE_SEGURANCA (Uso do global)
                confirmar = input(f"A venda de R$ {v:.2f} é legítima? (s/n): ").lower()
                if confirmar == 's':
                    novo_limite = float(input("Defina o novo LIMITE_SEGURANCA: "))
                    LIMITE_SEGURANCA = novo_limite
                    print(f"Limite atualizado para: R$ {LIMITE_SEGURANCA:.2f}")


        if media > LIMITE_SEGURANCA:
            print("\n!!! SISTEMA EM QUARENTENA !!!")
        else:
            print("\nStatus: Média dentro dos padrões de segurança.")


        print("\n--- Verificação de Integridade de Dados ---")
        print(f"Variável v1: {v1} | Tipo: {type(v1)}")
        print(f"Variável v2: {v2} | Tipo: {type(v2)}")
        print(f"Variável v3: {v3} | Tipo: {type(v3)}")
        print(f"Variável media: {media} | Tipo: {type(media)}")
        print(f"Variável LIMITE_SEGURANCA: {LIMITE_SEGURANCA} | Tipo: {type(LIMITE_SEGURANCA)}")

    except ValueError:
        print("\nErro: Por favor, insira apenas números decimais (use ponto em vez de vírgula).")


analisar_vendas()