# -*- coding: utf-8 -*-
"""projeto_matrizes_musicais .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bh5tI1LoLsgd5wbwOgaYGaX_5vHxV0D0
"""

biblioteca_musical = {

  "Toques": [

    {"Alegre": ([440, 480], [520, 560])},

    {"Triste": ([200, 150], [100, 50])}

  ]

}



nova_biblioteca = {"Toques": []}



for item in biblioteca_musical["Toques"]: # nível 1 (lista)

  novo_item = {}



  for nome, matriz in item.items(): # nível 2 (dicionário)

    linha1, linha2 = matriz



    # Transposição manual (2x2)

    transposta = (

      [linha1[0], linha2[0]],

      [linha1[1], linha2[1]]

    )



    novo_item[nome] = transposta



  nova_biblioteca["Toques"].append(novo_item)



# Exibir resultado

print(nova_biblioteca)