# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-76wW4kOgAXu9AEug5TCWuTKRCpMWmfH
"""



def simulador_evacuacao():



  locais = ["Quarto", "Cozinha", "Sala", "Porta", "Portão"]



  estados = [

    "caminho livre",

    "caminho livre",

    "tem chave",

    "porta trancada",

    "saida"

  ]



  posicao = 0

  tem_chave = False

  energia = 10



  print("INICIANDO EVACUACAO...\n")



  while energia > 0:



    print("Local atual:", locais[posicao])



    estado = estados[posicao]



    if estado == "caminho livre":

      print("Caminho livre, avançando...")

      posicao = posicao + 1



    elif estado == "tem chave":

      print("Voce encontrou a chave na sala!")

      tem_chave = True

      posicao = posicao + 1



    elif estado == "porta trancada":

      print("Porta trancada!")





      if tem_chave == True:

        print("Usou a chave e abriu a porta!")

        posicao = posicao + 1

      else:

        print("Sem chave, voltando...")

        posicao = posicao - 1



    elif estado == "saida":

      print("Voce saiu com sucesso!")

      break



    energia = energia - 1

    print("Energia restante:", energia, "\n")



  if energia == 0:

    print("O agente ficou sem energia!")





simulador_evacuacao()

simulador_evacuacao()

def simulador_evacuacao_interativo():
    # Mapeamento do ambiente
    locais = ["Quarto", "Cozinha", "Sala", "Porta", "Portão"]

    # Estados de cada local
    estados = [
        "caminho livre", # Quarto
        "caminho livre", # Cozinha
        "tem chave",     # Sala
        "porta trancada",# Porta
        "saida"          # Portão
    ]

    posicao = 0
    tem_chave = False
    energia = 15 # Aumentei a energia para dar tempo de explorar

    print("=== INTERFACE DE EVACUAÇÃO INTERATIVA ===")
    print("Comandos: [f] Frente | [t] Trás\n")

    while energia > 0:
        print(f"📍 Local atual: {locais[posicao]}")
        print(f"⚡ Energia: {energia}")

        # Verifica se encontrou a chave automaticamente ao chegar na Sala
        if estados[posicao] == "tem chave" and not tem_chave:
            print("🔑 Você encontrou a chave na Sala!")
            tem_chave = True

        # Verifica se chegou na saída
        if estados[posicao] == "saida":
            print("\n🏁 PARABÉNS! Você alcançou o portão e saiu com sucesso!")
            break

        # Pergunta a direção ao usuário
        direcao = input("Para onde deseja ir? (f/t): ").lower()

        if direcao == 'f':
            # Tenta avançar
            nova_posicao = posicao + 1

            # Bloqueio de limite do mapa
            if nova_posicao >= len(locais):
                print("❌ Não há nada além deste ponto.")
            # Bloqueio da Porta Trancada
            elif estados[nova_posicao] == "porta trancada" and not tem_chave:
                print("🔒 A porta está trancada! Você precisa da chave da Sala.")
            else:
                posicao = nova_posicao
                print("🏃 Avançando...")

        elif direcao == 't':
            # Tenta voltar
            if posicao > 0:
                posicao -= 1
                print("⬅️ Voltando...")
            else:
                print("❌ Você já está no início (Quarto).")

        else:
            print("⚠️ Comando inválido! Use 'f' para frente ou 't' para trás.")

        energia -= 1
        print("-" * 30)

    if energia == 0:
        print("\n💀 O agente ficou sem energia e não conseguiu sair!")

# Executar o novo simulador
simulador_evacuacao_interativo()

### PARTE 1: O Algoritmo do Microclima Loca





def analisar_microclima_temporal():

  dados_locais = [

    ["Praça Silvio Romero", [1, 29, 38, 41], [2, 29, 56, 40]],

    ["Avenida Marechal Tito", [1, 29, 40, 42], [2, 29, 41, 42]],

    ["Ponto de ônibus", [1, 30, 42, 39], [2, 30, 43, 39]]

  ]



  for local in dados_locais:

    nome_local = local[0]

    dias = local[1:]



    print(f"\n--- ANALISANDO: {nome_local}")



    for medicao in dias:

      dia, temp, umid, iqa = medicao





      match iqa:

        case i if i <= 40:

          qualidade = "Boa"

        case i if i <= 80:

          qualidade = "Moderada"

        case _:

          qualidade = "Ruim"





      penalidade_umidade = 2 if umid < 40 or umid > 70 else 0



      nota = 10 - (iqa * 0.03) - ((temp - 24) * 0.2) - penalidade_umidade





      if nota < 0:

        nota = 0



      nota_final = round(nota, 1)



      print(f"Dia: {dia} - Temp: {temp}°C - Umidade: {umid}% - IQA: {qualidade} - Nota: {nota_final}/10")





analisar_microclima_temporal()

analisar_microclima_temporal()

LIMITE_SEGURANCA = 15000.00

def analisar_vendas():
    global LIMITE_SEGURANCA
    print("--- Sistema de Auditoria de Vendas ---")

    try:

        v1 = float(input("Digite o valor da venda 1: "))
        v2 = float(input("Digite o valor da venda 2: "))
        v3 = float(input("Digite o valor da venda 3: "))
        vendas = [v1, v2, v3]


        media = sum(vendas) / len(vendas)
        print(f"\nMédia calculada: R$ {media:.2f}")


        for v in vendas:
            if v > (media * 5):
                print(f"\nALERTA: Discrepância detectada na venda de R$ {v:.2f}.")
                print("Sugestão: REVISÃO MANUAL.")

                # Permitir que o gerente altere o LIMITE_SEGURANCA (Uso do global)
                confirmar = input(f"A venda de R$ {v:.2f} é legítima? (s/n): ").lower()
                if confirmar == 's':
                    novo_limite = float(input("Defina o novo LIMITE_SEGURANCA: "))
                    LIMITE_SEGURANCA = novo_limite
                    print(f"Limite atualizado para: R$ {LIMITE_SEGURANCA:.2f}")


        if media > LIMITE_SEGURANCA:
            print("\n!!! SISTEMA EM QUARENTENA !!!")
        else:
            print("\nStatus: Média dentro dos padrões de segurança.")


        print("\n--- Verificação de Integridade de Dados ---")
        print(f"Variável v1: {v1} | Tipo: {type(v1)}")
        print(f"Variável v2: {v2} | Tipo: {type(v2)}")
        print(f"Variável v3: {v3} | Tipo: {type(v3)}")
        print(f"Variável media: {media} | Tipo: {type(media)}")
        print(f"Variável LIMITE_SEGURANCA: {LIMITE_SEGURANCA} | Tipo: {type(LIMITE_SEGURANCA)}")

    except ValueError:
        print("\nErro: Por favor, insira apenas números decimais (use ponto em vez de vírgula).")


analisar_vendas()