# -*- coding: utf-8 -*-
"""Sistema de Auditoria e Gestão de Orçamento Empresarial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-76wW4kOgAXu9AEug5TCWuTKRCpMWmfH
"""

import time

empresa = {

    'TI': {

        'Infraestrutura': 5000,
        'Desenvolvimento': 7000,
    },

    'RH': {

        'Recrutamento': 3000
    }
}

print(empresa)

for chave, valor in empresa.items():

    print(chave)
    print(valor)

for chave, valor in empresa.items():

    if type(valor) == dict:
        print(chave, 'é um dicionario')

    else:
        print(chave, 'é um numero')



def auditor(func):

    def wrapper(*args, **kwargs):

        inicio = time.time()

        resultado = func(*args, **kwargs)

        fim = time.time()

        print(f'Tempo: {fim - inicio:.4f} segundos')

        return resultado

    return wrapper



@auditor
def calcular_orcamento(dados, *ignorar, **kwargs):

    taxa = kwargs.get('taxa_cambio', 1)

    total = 0

    for chave, valor in dados.items():

        if chave in ignorar:
            continue

        if type(valor) == dict:

            total += calcular_orcamento(valor, *ignorar, **kwargs)

        else:

            total += valor * taxa

    return total


resultado = calcular_orcamento(empresa)

print('Total:', resultado)